### PR TITLE
Add function to upload submissions

### PR DESCRIPTION
**Pull request by philipcmonk**
Here's some boilerplate to upload a submission.  Please feel free to take this and restructure it any way you want.  For example, perhaps `upload_submission()` shouldn't be in the same class as `call()`

To use this, you'll need an API token.  Jonathan is working on a front end for them, but in the meantime, if you're logged in to the website, you can generate a token for yourself at the dev console with: 

```
MyApp.fetchApiTournament('mutation($password: String!, $code: String, $name: String!) {createApiToken(password: $password, code: $code, name: $name, scopes: ["upload_submission"]) {scopes secretKey publicId name}}', {password: "mypassword", code: "123456", name: "my first API token"}).then(console.log)
```

Obviously, replace your own password and optional 2FA token (if you don't have 2FA enabled, just omit those fields).

You'll get back an object that has a public id and a secret key.  You can use those to upload a submission:

```
>>> from api_tournament import ApiTournament
>>> a = ApiTournament("<PUBLIC-ID>", "<SECRET-KEY>")
>>> a.upload_submission("<FILE-PATH>")
```

### CODE REVIEW

**Comment by kwgoodman** [comment]
The first numerox PR! And it is flake8 clean with all unit tests passing!

**Comment by kwgoodman** [comment]
I'll see if the front end is ready to try tomorrow.

How do we check the status of a submission (loggloss, originality, ...)? Would we need a submissionid?

**Comment by philipcmonk** [comment]
Okay, I added a `read_submission_info` scope, so if you create a token with scope, you can use a query like this (with `APITournament.call()` in this PR):

```
query submissions {
  submissions(id: "812e2d27-4af8-411a-ab2c-e177d045dd1c") {
    originality {
      pending
      value
    }
    concordance {
      pending
      value
    }
    consistency
    validation_logloss
  }
}
```

Which will produce something like this:

```
{
  "data": {
    "submissions": [
      {
        "validation_logloss": 0.692459429265542,
        "originality": {
          "value": false,
          "pending": false
        },
        "consistency": 50,
        "concordance": {
          "value": true,
          "pending": false
        }
      }
    ]
  }
}
```

I just added a commit to return the submission ID from `upload_submission()`.

You can see what other scopes exist with this query:

```
query scopes {
  apiTokenScopes {
    description
    name
  }
}
```

**Comment by kwgoodman** [comment]
I have been unable to test the PR. I did upload a submission (R80) by following your example. It uploaded and appeared on the leaderboard (with logloss 1) but there were no results on the left panel. So in R81 I manually uploaded. Same results. Acct: numerox_test

**Comment by philipcmonk** [comment]
There is now an interface to generate API tokens here: https://numer.ai/account.

**Comment by kwgoodman** [comment]
That looks really nice!

**Comment by kwgoodman** [comment]
The front end gives me a public ID. Do I also need a secret key like in your example:
```
>>> a = ApiTournament("<PUBLIC-ID>", "<SECRET-KEY>")
```

**Comment by philipcmonk** [comment]
You do need the secret key.  When you generate a key, the secret should be shown in the banner thingy at the bottom.

**Comment by kwgoodman** [comment]
Yep. Thanks for the hand holding.

**Pull request merged**
